### ISSUE TITLE
Assertion errors should have real warning messages

### ISSUE THREAD

**Issue by swo** [CDCgov/pygriddler#23]
This was not helpful:

```
>>> griddler.griddle.read('eda/params_py.yaml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ulp7/.cache/pypoetry/virtualenvs/dxviz-Jn4HUAO5-py3.10/lib/python3.10/site-packages/griddler/griddle.py", line 105, in read
    return parse(raw)
  File "/home/ulp7/.cache/pypoetry/virtualenvs/dxviz-Jn4HUAO5-py3.10/lib/python3.10/site-packages/griddler/griddle.py", line 42, in parse
    validate(griddle)
  File "/home/ulp7/.cache/pypoetry/virtualenvs/dxviz-Jn4HUAO5-py3.10/lib/python3.10/site-packages/griddler/griddle.py", line 17, in validate
    assert all(
AssertionError
```

**Comment by swo** [comment]
Not sufficiently detailed
